menu:
    Blog: /
    Archive: /archives/
    About: /about/
    Rss: /atom.xml

favicon: /favicon.png
logo: /img/logo.png
logo2x: /img/logo@2x.png
logo3x: /img/logo@3x.png
themeColor: "#d66329"

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-65933410-1

# Copyright Infomation
startyear: 2009

# Node sass Config
# see https://github.com/sass/node-sass
node_sass:
